name: 'chromatic'
on:
  push:
    branches:
      - master
    paths:
      - 'tailwindcss-design-system/**'

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: Checkout branch
      uses: actions/checkout@v1

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies and deploy storybook
      run: cd tailwindcss-design-system && yarn install && npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} --exit-zero-on-changes
